// Generated by CoffeeScript 1.7.1
(function() {
  var addMachine, gspeed, mkrandom, opt, run, send_json, speed, update, vmindex, vmnumbe;

  speed = {};

  gspeed = {};

  vmindex = {};

  vmnumbe = 0;

  update = function(name, dataset, x) {
    var count0, count1, mspeed, num, q0, q1, sum0, sum1, vm, _results;
    mspeed = gspeed[name];
    console.log(JSON.stringify(gspeed));
    console.log(mspeed);
    q0 = mspeed["Queue0"];
    q1 = mspeed["Queue1"];
    count0 = 0;
    count1 = 0;
    sum0 = 0;
    sum1 = 0;
    num = q0.length;
    for (vm in q0) {
      sum0 += q0[vm];
    }
    for (vm in q1) {
      sum1 += q1[vm];
    }
    _results = [];
    for (vm in q0) {
      dataset[vm].addPoint([x, sum0 - count0], true, true);
      count0 += q0[vm];
      count1 += q1[vm];
      _results.push(dataset[2 * num - vm - 1].addPoint([x, -count1], true, true));
    }
    return _results;
  };

  send_json = function(mes) {
    var json, name, _results;
    json = eval('(' + mes + ')');
    if (("type" in json) && (json["type"] === "setup")) {
      _results = [];
      for (name in json["machines"]) {
        console.log(name);
        $("#main").append("<div id='" + name + "' class ='col-md-6 machine'></div>");
        _results.push(mkchart("#" + name, update, json["machines"][name]));
      }
      return _results;
    } else if (("type" in json) && (json["type"] === "log")) {
      return $("#log").append(json["msg"]);
    } else {
      return gspeed = json['speed'];
    }
  };

  opt = {
    type: "setup",
    machines: {
      m0: {
        num: 2,
        name: "Qiao"
      },
      m1: {
        num: 2,
        name: "Chu"
      }
    }
  };

  send_json(JSON.stringify(opt));

  speed = {};

  addMachine = function(name) {
    var a, q, _results;
    speed[name] = {};
    speed[name]["Queue0"] = [];
    speed[name]["Queue1"] = [];
    _results = [];
    for (a in speed[name]) {
      q = speed[name][a];
      q[0] = 0;
      _results.push(q[1] = 0);
    }
    return _results;
  };

  addMachine("Qiao");

  addMachine("Chu");

  mkrandom = function(name) {
    var a, q, _results;
    _results = [];
    for (a in speed[name]) {
      q = speed[name][a];
      q[0] = Math.random() * 100;
      _results.push(q[1] = Math.random() * 100);
    }
    return _results;
  };

  run = function() {
    var a, data;
    for (a in speed) {
      mkrandom(a);
    }
    data = {
      'speed': speed
    };
    return send_json(JSON.stringify(data));
  };

  setInterval(run, 1000);

}).call(this);
