// Generated by CoffeeScript 1.7.1
(function() {
  var init_connect, speed, update;

  speed = {};

  update = function(dataset, x) {
    var y;
    y = speed;
    dataset[0].addPoint([x, y[0]], true, true);
    dataset[1].addPoint([x, y[1]], true, true);
    dataset[2].addPoint([x, y[2]], true, true);
    return console.log(x + y);
  };

  init_connect = function(data) {
    var socket;
    socket = io.connect(document.domain);
    socket.on('connect', function() {
      mkchart("#container", update);
      mkchart("#container1", update);
      mkchart("#container2", update);
      mkchart("#container3", update);
      mkchart("#container4", update);
      mkchart("#container5", update);
      return console.log("Connected");
    });
    socket.on("disconnect", function() {
      return console.log("disConnect");
    });
    return socket.on("message", function(mes) {
      var json;
      json = eval('(' + mes + ')');
      return speed = json['speed'];
    });
  };

  init_connect();

}).call(this);
