// Generated by CoffeeScript 1.7.1
(function() {
  var app, io, run, server;

  app = (require('express'))();

  server = (require('http')).createServer(app);

  io = (require('socket.io')).listen(server);

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/index.html');
  });

  app.get('/js/*', function(req, res) {
    return res.sendfile(__dirname + req.path);
  });

  app.get('/css/*', function(req, res) {
    return res.sendfile(__dirname + req.path);
  });

  run = (require('./getStream')).update;

  io.sockets.on('connection', function(socket) {
    console.log("Connected");
    return setInterval(run, 1000, socket);
  });

  server.listen(8080);

}).call(this);
