// Generated by CoffeeScript 1.7.1
(function() {
  var addMachine, mkrandom, run, speed, update;

  speed = {};

  addMachine = function(name) {
    var a, q, _results;
    speed[name] = {};
    speed[name]["Queue0"] = [];
    speed[name]["Queue1"] = [];
    _results = [];
    for (a in speed[name]) {
      q = speed[name][a];
      q[0] = 0;
      _results.push(q[1] = 0);
    }
    return _results;
  };

  mkrandom = function(name) {
    var a, q, _results;
    _results = [];
    for (a in speed[name]) {
      q = speed[name][a];
      q[0] = Math.random() * 100;
      _results.push(q[1] = Math.random() * 100);
    }
    return _results;
  };

  run = function() {
    var a, _results;
    _results = [];
    for (a in speed) {
      _results.push(mkrandom(a));
    }
    return _results;
  };

  setInterval(run, 1000);

  addMachine("Yang");

  addMachine("Qixin");

  update = function(socket) {
    var data;
    data = {
      'speed': speed
    };
    return socket.send(JSON.stringify(data));
  };

  exports.update = update;

}).call(this);
