// Generated by CoffeeScript 1.7.1
(function() {
  var cb, cluster, http, machine, opt, port, proc, run;

  http = require("http");

  opt = {
    host: "202.38.88.62",
    path: "/wm/core/switch/00:00:00:00:00:00:00:01/port/json",
    port: 8010
  };

  cb = function(res) {
    var str;
    str = '';
    res.on('data', function(chunk) {
      return str = str + chunk;
    });
    return res.on('end', function(chunk) {
      return proc(str);
    });
  };

  cluster = {};

  port = (function() {
    function port(name) {
      this.name = name;
      this.speed = 0;
      this.last = {};
    }

    port.prototype.proc = function(aport) {
      this.speed = aport['transmitBytes'] + aport['receiveBytes'] - this.last['transmitBytes'] - this.last['receiveBytes'];
      return this.last = aport;
    };

    return port;

  })();

  machine = (function() {
    function machine(name) {
      this.name = name;
      this.ports = {};
      this.speed = 0;
    }

    machine.prototype.procpermachine = function(portlist) {
      var aport, name, speed, _i, _len;
      for (_i = 0, _len = portlist.length; _i < _len; _i++) {
        aport = portlist[_i];
        name = aport["portNumber"];
        if (ports[name] === void 0) {
          port[name] = new port(name);
          port.last = aport;
        } else {
          port[name].proc(aport);
        }
      }
      speed = 0;
      for (port in this.ports) {
        this.speed += this.ports[port].speed;
      }
      return console.log(this.speed);
    };

    return machine;

  })();

  proc = function(str) {
    var json, name, _results;
    json = eval("(" + str + ")");
    _results = [];
    for (name in json) {
      if (cluster[name] === void 0) {
        cluster[name] = new machine(name);
      }
      _results.push(machine.procpermachine(json[name]));
    }
    return _results;
  };

  run = function() {
    var a;
    a = http.request(opt, cb);
    a.end();
    return console.log("Tick");
  };

  setInterval(run, 1000);

}).call(this);
