// Generated by CoffeeScript 1.7.1
(function() {
  var a, cb, http, opt;

  http = require("http");

  opt = {
    host: "www.google.com",
    path: "/"
  };

  cb = function(res) {
    return res.on('data', function(chunk) {
      return console.log(chunk);
    });
  };

  a = http.request(opt, cb);

  a.end();

}).call(this);
